#! /bin/sh

# Settings

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding		 26 
#bspc config bottom_padding	 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_struts   true
bspc config focus_follows_pointer true

bspc rule -a brave desktop='^1'
bspc rule -a discord desktop='^2'
bspc rule -a obs desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

# Border
bspc config focused_border_color        "#8FBCBB"
bspc config normal_border_color         "#3B4252"
bspc config active_border_color         "#8fbcbb"

# Autastart

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --set-scaled /usr/share/backgrounds/nordic-wallpapers/archlinux.png &
sh ~/.config/polybar/launch.sh &
nm-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sh ~/.config/obs-studio/autostart.sh &
discord-canary
